# Generated by Django 5.0.7 on 2025-06-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
